services:
  url:
    config: 192.168.1.10
    keycloak: 192.168.1.10
    eureka: 192.168.1.10
spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://${services.url.config}:8888"
server:
  port: 9111