apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      role: api-gateway
  template:
    metadata:
      labels:
        role: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ajorge2893/api-gateway
        env:
        - name: SERVICES_URL_CONFIG
          value: config-server
        - name: SERVICES_URL_EUREKA
          value: eureka-server
        - name: SERVICES_URL_KEYCLOAK
          value: "20.96.44.112"
        ports:
        - containerPort: 9111
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: LoadBalancer
  ports:
  - port: 9111
    targetPort: 9111
  selector:
    role: api-gateway