apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  selector:
    matchLabels:
      role: eureka-server
  template:
    metadata:
      labels:
        role: eureka-server
    spec:
      containers:
      - name: eureka-server
        image: ajorge2893/eureka-server
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
spec:
  type: LoadBalancer
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    role: eureka-server