apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db
spec:
  selector:
    matchLabels:
      role: mongo-db
  template:
    metadata:
      labels:
        role: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: mongo
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    role: mongo-db