apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
spec:
  selector:
    matchLabels:
      role: mysql-db
  template:
    metadata:
      labels:
        role: mysql-db
    spec:
      containers:
      - name: mysql-db
        image: mysql:5.6
        env:
        - name: MYSQL_DATABASE
          value: "servicedb"
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-db
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    role: mysql-db