apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  replicas: 2
  selector:
    matchLabels:
      role: payments
  template:
    metadata:
      labels:
        role: payments
    spec:
      containers:
      - name: payments
        image: ajorge2893/payments
        env:
        - name: SERVICES_URL_CONFIG
          value: config-server
        - name: SERVICES_URL_REDIS-CACHE
          value: redis-cache
        - name: SERVICES_URL_SERVICE-PAYMENT
          value: servicing-payment
        - name: SERVICES_URL_FAVORITE
          value: favorites
        - name: SERVICES_URL_EUREKA
          value: eureka-server
        - name: SERVICES_URL_KEYCLOAK
          value: "20.96.44.112"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: payments
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    role: payments