apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cache
spec:
  selector:
    matchLabels:
      role: redis-cache
  template:
    metadata:
      labels:
        role: redis-cache
    spec:
      containers:
      - name: redis-cache
        image: redis
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    role: redis-cache