apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicing-payment
spec:
  replicas: 2
  selector:
    matchLabels:
      role: servicing-payment
  template:
    metadata:
      labels:
        role: servicing-payment
    spec:
      containers:
      - name: servicing-payment
        image: ajorge2893/servicing-payment
        env:
        - name: SERVICES_URL_CONFIG
          value: config-server
        - name: SERVICES_URL_MONGODB
          value: mongo-db
        - name: SERVICES_URL_EUREKA
          value: eureka-server
        - name: SERVICES_URL_KEYCLOAK
          value: "20.96.44.112"
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: servicing-payment
spec:
  ports:
  - port: 8082
    targetPort: 8082
  selector:
    role: servicing-payment